services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"         
      - "4510-4559:4510-4559" 
    environment:
      - SERVICES=dynamodb,s3,cloudformation,iam
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - localstack_volume:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  localstack_volume:
